---
# SPDX-FileCopyrightText: 2021 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
categories:
  - title: ":boom: Breaking Change :boom:"
    labels:
      - "breaking-change"
  - title: ":zap: Enhancements :zap:"
    labels:
      - "enhancement"
  - title: ":sparkles: New Features :sparkles:"
    labels:
      - "feature"
  - title: ":bug: Bug Fixes :bug:"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: ":wrench: Maintenance :wrench:"
    labels:
      - "chore"
      - "documentation"
      - "maintenance"
      - "repo"
      - "dependencies"
      - "github_actions"
      - "refactor"
  - title: ":mortar_board: Code Quality :mortar_board:"
    labels:
      - "code-quality"
      - "CI"
      - "test"
autolabeler:
  - label: "breaking-change"
    title:
      - "/!:/i"
  - label: "feature"
    title:
      - "/feat:/i"
  - label: "bug"
    title:
      - "/fix:/i"
  - label: "refactor"
    title:
      - "/refactor:/i"
  - label: "code-quality"
    title:
      - "/test:/i"
  - label: "CI"
    title:
      - "/ci:/i"
  - label: "chore"
    title:
      - "/chore:/i"
  - label: "documentation"
    title:
      - "/docs:/i"
# yamllint disable rule:line-length
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/os-climate/osc-github-devops/v$RESOLVED_VERSION/total.svg)](https://github.com/os-climate/osc-github-devops/releases/v$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/os-climate/osc-github-devops/issues)
