name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  python-version: "3.8"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Setup Python"
      uses: actions/setup-python@v4.7.0
      with:
        python-version: ${{ env.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run auto-tests
      run: tox
